name: Run Main.py

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository content
        uses: actions/checkout@v2 # checkout the repository content to GitHub runner

      - name: List directory contents
        run: ls -R

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # install the Python version needed
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install p7zip
        run: sudo apt-get update && sudo apt-get install p7zip-full -y

      - name: Extract encrypted.zip
        run: echo "${{ secrets.ZIP_PASSWORD }}" | 7z x -p- encrypted.zip -oextracted_files
          
      - name: Execute Main.py script
        run: python extracted_files/main.py
        env:
          PLAYLIST_URL: ${{ secrets.PLAYLIST_URL }} # Load the playlist URL from GitHub secrets
          PASSWORD: ${{ secrets.PASSWORD }} # Load the secret password from GitHub secrets
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "👉 Updated HLS Links" --allow-empty)
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
